Automatic Snapshot Tests
lukinco/cra-template-lukin pull request #1
Opened 2020-03-30 19:28 UTC by mauriciord

## Description
This solution includes an **Automatic Snapshot generation** based on components stories files.
It's using the [StoryShots Addon](https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-core)

2020-04-09 01:35 UTC, mauriciord commented
@fdaciuk @diogomoretti

2020-04-09 13:16 UTC, fdaciuk commented
Hey @mauriciord! Thanks man :)
I'll check this later today :)

2020-04-14 13:23 UTC, fdaciuk requested changes
Fala @mauriciord! Obrigado pelo PR! Antes de fazer o merge, consegue só fazer os ajustes solicitados ali? Valeu!

2020-04-14 13:23 UTC, fdaciuk commented on template.json
> +      "react-test-renderer": "16.13.1",
Remover essa dep

2020-04-14 13:23 UTC, fdaciuk commented on template.json
> +      "extends": ["react-app", "standard", "standard-react"],
Voltar como estava

2020-04-14 13:23 UTC, fdaciuk commented on template.json
> +        ]
Voltar como estava

2020-04-14 13:23 UTC, fdaciuk commented on template.json
> +      "plugins": ["only-warn"]
Voltar como estava

2020-04-14 13:23 UTC, fdaciuk commented on template.json
> +    "rescripts": ["env"],
Voltar como estava

2020-04-14 13:23 UTC, fdaciuk commented on template.json
> +      "globals": ["fetch", "test", "expect"]
Voltar como estava

2020-04-14 14:12 UTC, mauriciord commented
@fdaciuk Resolvido conforme solicitado.
Muito obrigado pelo review.

2020-04-14 14:25 UTC, fdaciuk commented
Perfeito meu caro! Obrigado pela contribuição :clap: :clap: :woman_dancing: :woman_dancing:

2020-04-14 14:26 UTC, merged